--- Highlight groups for commonly used plugins. Defining these is harmless when
--- the plugin is not installed, so they are always registered.

local util = require("light-modern.util")

local M = {}

function M.get(c, opts)
  local bg = opts.transparent and c.none or c.bg
  local bg_sidebar = opts.transparent and c.none or c.bg_alt
  local bg_float = opts.transparent and c.none or c.bg_float

  return {
    ---------------------------------------------------------------------------
    -- gitsigns.nvim
    ---------------------------------------------------------------------------
    GitSignsAdd            = { fg = c.added },
    GitSignsChange         = { fg = c.changed },
    GitSignsDelete         = { fg = c.removed },
    GitSignsAddNr          = { fg = c.added },
    GitSignsChangeNr       = { fg = c.changed },
    GitSignsDeleteNr       = { fg = c.removed },
    GitSignsAddLn          = { bg = c.diff_add },
    GitSignsChangeLn       = { bg = c.diff_change },
    GitSignsDeleteLn       = { bg = c.diff_delete },
    GitSignsAddInline      = { bg = c.diff_text },
    GitSignsChangeInline   = { bg = c.diff_text },
    GitSignsDeleteInline   = { bg = c.diff_delete },
    GitSignsCurrentLineBlame = { fg = c.fg_muted, italic = true },

    ---------------------------------------------------------------------------
    -- telescope.nvim
    ---------------------------------------------------------------------------
    TelescopeNormal        = { fg = c.fg, bg = bg_float },
    TelescopeBorder        = { fg = c.border_alt, bg = bg_float },
    TelescopeTitle         = { fg = c.bg, bg = c.accent, bold = true },
    TelescopePromptNormal  = { fg = c.fg, bg = opts.transparent and c.none or c.bg },
    TelescopePromptBorder  = { fg = c.border_alt, bg = opts.transparent and c.none or c.bg },
    TelescopePromptTitle   = { fg = c.bg, bg = c.accent, bold = true },
    TelescopePromptPrefix  = { fg = c.accent },
    TelescopePromptCounter = { fg = c.fg_muted },
    TelescopeResultsTitle  = { fg = c.bg_float, bg = c.bg_float },
    TelescopePreviewTitle  = { fg = c.bg, bg = c.ok, bold = true },
    TelescopeSelection     = { fg = c.fg_editor, bg = c.bg_sel, bold = true },
    TelescopeSelectionCaret = { fg = c.accent, bg = c.bg_sel },
    TelescopeMultiSelection = { fg = c.accent },
    TelescopeMatching      = { fg = c.accent, bold = true },
    TelescopeResultsComment = { fg = c.fg_muted },
    TelescopeResultsDiffAdd = { fg = c.added },
    TelescopeResultsDiffChange = { fg = c.changed },
    TelescopeResultsDiffDelete = { fg = c.removed },

    ---------------------------------------------------------------------------
    -- fzf-lua
    ---------------------------------------------------------------------------
    FzfLuaNormal           = { fg = c.fg, bg = bg_float },
    FzfLuaBorder           = { fg = c.border_alt, bg = bg_float },
    FzfLuaTitle            = { fg = c.bg, bg = c.accent, bold = true },
    FzfLuaCursorLine       = { bg = c.bg_sel, bold = true },
    FzfLuaFzfMatch         = { fg = c.accent, bold = true },
    FzfLuaHeaderBind       = { fg = c.control },
    FzfLuaHeaderText       = { fg = c.fg_dim },
    FzfLuaPathLineNr       = { fg = c.line_nr },
    FzfLuaPathColNr        = { fg = c.line_nr },
    FzfLuaBufNr            = { fg = c.number },
    FzfLuaLiveSym          = { fg = c.func },

    ---------------------------------------------------------------------------
    -- nvim-tree
    ---------------------------------------------------------------------------
    NvimTreeNormal         = { fg = c.fg, bg = bg_sidebar },
    NvimTreeNormalNC       = { fg = c.fg, bg = bg_sidebar },
    NvimTreeWinSeparator   = { fg = c.border, bg = bg_sidebar },
    NvimTreeEndOfBuffer    = { fg = bg_sidebar, bg = bg_sidebar },
    NvimTreeRootFolder     = { fg = c.fg, bold = true },
    NvimTreeFolderName     = { fg = c.fg },
    NvimTreeOpenedFolderName = { fg = c.fg, bold = true },
    NvimTreeEmptyFolderName  = { fg = c.fg_dimmer },
    NvimTreeFolderIcon     = { fg = c.fg_dim },
    NvimTreeFileIcon       = { fg = c.fg_dim },
    NvimTreeIndentMarker   = { fg = c.indent },
    NvimTreeSymlink        = { fg = c.type },
    NvimTreeSpecialFile    = { fg = c.control },
    NvimTreeExecFile       = { fg = c.added },
    NvimTreeImageFile      = { fg = c.fg },
    NvimTreeOpenedFile     = { fg = c.fg, bold = true },
    NvimTreeCursorLine     = { bg = c.bg_sel },
    NvimTreeGitNew         = { fg = c.added },
    NvimTreeGitDirty       = { fg = c.warn },
    NvimTreeGitStaged      = { fg = c.added },
    NvimTreeGitMerge       = { fg = c.control },
    NvimTreeGitRenamed     = { fg = c.changed },
    NvimTreeGitDeleted     = { fg = c.removed },

    ---------------------------------------------------------------------------
    -- neo-tree.nvim
    ---------------------------------------------------------------------------
    NeoTreeNormal          = { fg = c.fg, bg = bg_sidebar },
    NeoTreeNormalNC        = { fg = c.fg, bg = bg_sidebar },
    NeoTreeWinSeparator    = { fg = c.border, bg = bg_sidebar },
    NeoTreeEndOfBuffer     = { fg = bg_sidebar, bg = bg_sidebar },
    NeoTreeRootName        = { fg = c.fg, bold = true },
    NeoTreeDirectoryName   = { fg = c.fg },
    NeoTreeDirectoryIcon   = { fg = c.fg_dim },
    NeoTreeFileName        = { fg = c.fg },
    NeoTreeFileIcon        = { fg = c.fg_dim },
    NeoTreeFileNameOpened  = { fg = c.fg, bold = true },
    NeoTreeIndentMarker    = { fg = c.indent },
    NeoTreeExpander        = { fg = c.fg_dim },
    NeoTreeSymbolicLinkTarget = { fg = c.type },
    NeoTreeCursorLine      = { bg = c.bg_sel },
    NeoTreeTitleBar        = { fg = c.bg, bg = c.accent },
    NeoTreeDimText         = { fg = c.fg_dimmer },
    NeoTreeGitAdded        = { fg = c.added },
    NeoTreeGitModified     = { fg = c.warn },
    NeoTreeGitDeleted      = { fg = c.removed },
    NeoTreeGitStaged       = { fg = c.added },
    NeoTreeGitUntracked    = { fg = c.fg_dimmer },
    NeoTreeGitConflict     = { fg = c.control },
    NeoTreeGitIgnored      = { fg = c.fg_dimmer },
    NeoTreeTabActive       = { fg = c.fg, bg = bg, bold = true },
    NeoTreeTabInactive     = { fg = c.fg_dimmer, bg = bg_sidebar },
    NeoTreeTabSeparatorActive   = { fg = c.accent, bg = bg },
    NeoTreeTabSeparatorInactive = { fg = c.border, bg = bg_sidebar },

    ---------------------------------------------------------------------------
    -- oil.nvim / mini.files
    ---------------------------------------------------------------------------
    OilDir                 = { fg = c.accent },
    OilDirIcon             = { fg = c.fg_dim },
    OilLink                = { fg = c.type },
    OilLinkTarget          = { fg = c.type },
    OilCopy                = { fg = c.added },
    OilMove                = { fg = c.changed },
    OilPurge               = { fg = c.removed },
    OilCreate              = { fg = c.added },
    OilDelete              = { fg = c.removed },
    MiniFilesTitle         = { fg = c.fg_dim },
    MiniFilesTitleFocused  = { fg = c.accent, bold = true },
    MiniFilesBorder        = { fg = c.border_alt, bg = bg_float },
    MiniFilesNormal        = { fg = c.fg, bg = bg_float },
    MiniFilesDirectory     = { fg = c.accent },
    MiniFilesFile          = { fg = c.fg },
    MiniFilesCursorLine    = { bg = c.bg_sel },

    ---------------------------------------------------------------------------
    -- nvim-cmp
    ---------------------------------------------------------------------------
    CmpDocumentation       = { fg = c.fg, bg = bg_float },
    CmpDocumentationBorder = { fg = c.border_alt, bg = bg_float },
    CmpItemAbbr            = { fg = c.fg },
    CmpItemAbbrDeprecated  = { fg = c.fg_muted, strikethrough = true },
    CmpItemAbbrMatch       = { fg = c.accent, bold = true },
    CmpItemAbbrMatchFuzzy  = { fg = c.accent, bold = true },
    CmpItemMenu            = { fg = c.fg_muted },
    CmpItemKindDefault     = { fg = c.fg_dim },
    CmpItemKindText        = { fg = c.fg },
    CmpItemKindMethod      = { fg = c.func },
    CmpItemKindFunction    = { fg = c.func },
    CmpItemKindConstructor = { fg = c.type },
    CmpItemKindField       = { fg = c.variable },
    CmpItemKindVariable    = { fg = c.variable },
    CmpItemKindClass       = { fg = c.type },
    CmpItemKindInterface   = { fg = c.type },
    CmpItemKindModule      = { fg = c.type },
    CmpItemKindProperty    = { fg = c.variable },
    CmpItemKindUnit        = { fg = c.number },
    CmpItemKindValue       = { fg = c.number },
    CmpItemKindEnum        = { fg = c.type },
    CmpItemKindKeyword     = { fg = c.keyword },
    CmpItemKindSnippet     = { fg = c.control },
    CmpItemKindColor       = { fg = c.property_value },
    CmpItemKindFile        = { fg = c.fg },
    CmpItemKindReference   = { fg = c.variable },
    CmpItemKindFolder      = { fg = c.fg },
    CmpItemKindEnumMember  = { fg = c.constant },
    CmpItemKindConstant    = { fg = c.constant },
    CmpItemKindStruct      = { fg = c.type },
    CmpItemKindEvent       = { fg = c.variable },
    CmpItemKindOperator    = { fg = c.operator },
    CmpItemKindTypeParameter = { fg = c.type },
    CmpItemKindCopilot     = { fg = c.ok },
    CmpGhostText           = { fg = c.fg_muted, italic = true },

    ---------------------------------------------------------------------------
    -- blink.cmp
    ---------------------------------------------------------------------------
    BlinkCmpMenu               = { fg = c.fg, bg = bg_float },
    BlinkCmpMenuBorder         = { fg = c.border_alt, bg = bg_float },
    BlinkCmpMenuSelection      = { fg = c.fg_editor, bg = c.bg_sel, bold = true },
    BlinkCmpScrollBarThumb     = { bg = c.border_alt },
    BlinkCmpScrollBarGutter    = { bg = c.bg_dark },
    BlinkCmpLabel              = { fg = c.fg },
    BlinkCmpLabelDeprecated    = { fg = c.fg_muted, strikethrough = true },
    BlinkCmpLabelMatch         = { fg = c.accent, bold = true },
    BlinkCmpLabelDetail        = { fg = c.fg_muted },
    BlinkCmpLabelDescription   = { fg = c.fg_muted },
    BlinkCmpKind               = { fg = c.fg_dim },
    BlinkCmpSource             = { fg = c.fg_muted },
    BlinkCmpGhostText          = { fg = c.fg_muted, italic = true },
    BlinkCmpDoc                = { fg = c.fg, bg = bg_float },
    BlinkCmpDocBorder          = { fg = c.border_alt, bg = bg_float },
    BlinkCmpDocSeparator       = { fg = c.border },
    BlinkCmpDocCursorLine      = { bg = c.bg_sel },
    BlinkCmpSignatureHelp      = { fg = c.fg, bg = bg_float },
    BlinkCmpSignatureHelpBorder = { fg = c.border_alt, bg = bg_float },
    BlinkCmpSignatureHelpActiveParameter = { bg = c.accent_soft, bold = true },

    ---------------------------------------------------------------------------
    -- bufferline.nvim
    ---------------------------------------------------------------------------
    BufferLineFill              = { bg = c.bg_alt },
    BufferLineBackground        = { fg = c.fg_dimmer, bg = c.bg_alt },
    BufferLineBufferVisible     = { fg = c.fg_dimmer, bg = c.bg_alt },
    BufferLineBufferSelected    = { fg = c.fg, bg = bg, bold = true },
    BufferLineTab               = { fg = c.fg_dimmer, bg = c.bg_alt },
    BufferLineTabSelected       = { fg = c.accent, bg = bg, bold = true },
    BufferLineTabClose          = { fg = c.fg_dim, bg = c.bg_alt },
    BufferLineIndicatorSelected = { fg = c.accent, bg = bg },
    BufferLineSeparator         = { fg = c.border, bg = c.bg_alt },
    BufferLineSeparatorVisible  = { fg = c.border, bg = c.bg_alt },
    BufferLineSeparatorSelected = { fg = c.border, bg = bg },
    BufferLineCloseButton       = { fg = c.fg_dim, bg = c.bg_alt },
    BufferLineCloseButtonVisible= { fg = c.fg_dim, bg = c.bg_alt },
    BufferLineCloseButtonSelected = { fg = c.fg, bg = bg },
    BufferLineModified          = { fg = c.warn, bg = c.bg_alt },
    BufferLineModifiedVisible   = { fg = c.warn, bg = c.bg_alt },
    BufferLineModifiedSelected  = { fg = c.warn, bg = bg },
    BufferLineDuplicate         = { fg = c.fg_dimmer, bg = c.bg_alt, italic = true },
    BufferLineDuplicateSelected = { fg = c.fg_dim, bg = bg, italic = true },
    BufferLineNumbers           = { fg = c.fg_dimmer, bg = c.bg_alt },
    BufferLineNumbersSelected   = { fg = c.fg, bg = bg, bold = true },
    BufferLineError             = { fg = c.error, bg = c.bg_alt },
    BufferLineErrorSelected     = { fg = c.error, bg = bg },
    BufferLineWarning           = { fg = c.warn, bg = c.bg_alt },
    BufferLineWarningSelected   = { fg = c.warn, bg = bg },
    BufferLineInfo              = { fg = c.info, bg = c.bg_alt },
    BufferLineInfoSelected      = { fg = c.info, bg = bg },
    BufferLineHint              = { fg = c.hint, bg = c.bg_alt },
    BufferLineHintSelected      = { fg = c.hint, bg = bg },
    BufferLinePick              = { fg = c.error, bg = c.bg_alt, bold = true },
    BufferLinePickSelected      = { fg = c.error, bg = bg, bold = true },
    BufferLineOffsetSeparator   = { fg = c.border, bg = c.bg_alt },

    ---------------------------------------------------------------------------
    -- indent-blankline (v3 `ibl`) and mini.indentscope
    ---------------------------------------------------------------------------
    IblIndent              = { fg = c.indent },
    IblWhitespace          = { fg = c.indent },
    IblScope               = { fg = c.indent_active },
    IndentBlanklineChar    = { fg = c.indent },
    IndentBlanklineContextChar = { fg = c.indent_active },
    MiniIndentscopeSymbol  = { fg = c.indent_active },
    MiniIndentscopePrefix  = { nocombine = true },

    ---------------------------------------------------------------------------
    -- which-key.nvim
    ---------------------------------------------------------------------------
    WhichKey               = { fg = c.control },
    WhichKeyGroup          = { fg = c.accent },
    WhichKeyDesc           = { fg = c.fg },
    WhichKeySeparator      = { fg = c.fg_muted },
    WhichKeyFloat          = { bg = bg_float },
    WhichKeyBorder         = { fg = c.border_alt, bg = bg_float },
    WhichKeyValue          = { fg = c.fg_muted },
    WhichKeyIcon           = { fg = c.fg_dim },
    WhichKeyTitle          = { fg = c.accent, bg = bg_float, bold = true },

    ---------------------------------------------------------------------------
    -- noice.nvim / nvim-notify
    ---------------------------------------------------------------------------
    NoiceCmdline           = { fg = c.fg, bg = bg_float },
    NoiceCmdlineIcon       = { fg = c.accent },
    NoiceCmdlinePopup      = { fg = c.fg, bg = bg_float },
    NoiceCmdlinePopupBorder= { fg = c.border_alt, bg = bg_float },
    NoiceCmdlinePopupTitle = { fg = c.accent, bold = true },
    NoiceCmdlinePrompt     = { fg = c.fg },
    NoiceConfirm           = { fg = c.fg, bg = bg_float },
    NoiceConfirmBorder     = { fg = c.border_alt, bg = bg_float },
    NoiceMini              = { fg = c.fg, bg = c.bg_alt },
    NoiceVirtualText       = { fg = c.fg_muted },
    NoicePopupBorder       = { fg = c.border_alt, bg = bg_float },
    NoiceLspProgressTitle  = { fg = c.fg },
    NoiceLspProgressClient = { fg = c.accent },
    NoiceLspProgressSpinner= { fg = c.control },

    NotifyERRORBorder      = { fg = util.blend(c.error, c.bg, 0.4), bg = bg_float },
    NotifyWARNBorder       = { fg = util.blend(c.warn, c.bg, 0.4), bg = bg_float },
    NotifyINFOBorder       = { fg = util.blend(c.info, c.bg, 0.4), bg = bg_float },
    NotifyDEBUGBorder      = { fg = c.border_alt, bg = bg_float },
    NotifyTRACEBorder      = { fg = util.blend(c.control, c.bg, 0.4), bg = bg_float },
    NotifyERRORIcon        = { fg = c.error },
    NotifyWARNIcon         = { fg = c.warn },
    NotifyINFOIcon         = { fg = c.info },
    NotifyDEBUGIcon        = { fg = c.fg_dim },
    NotifyTRACEIcon        = { fg = c.control },
    NotifyERRORTitle       = { fg = c.error, bold = true },
    NotifyWARNTitle        = { fg = c.warn, bold = true },
    NotifyINFOTitle        = { fg = c.info, bold = true },
    NotifyDEBUGTitle       = { fg = c.fg_dim, bold = true },
    NotifyTRACETitle       = { fg = c.control, bold = true },
    NotifyERRORBody        = { fg = c.fg, bg = bg_float },
    NotifyWARNBody         = { fg = c.fg, bg = bg_float },
    NotifyINFOBody         = { fg = c.fg, bg = bg_float },
    NotifyDEBUGBody        = { fg = c.fg, bg = bg_float },
    NotifyTRACEBody        = { fg = c.fg, bg = bg_float },

    ---------------------------------------------------------------------------
    -- snacks.nvim
    ---------------------------------------------------------------------------
    SnacksNormal           = { fg = c.fg, bg = bg_float },
    SnacksWinBar           = { fg = c.fg, bg = c.bg_alt, bold = true },
    SnacksBackdrop         = { bg = c.bg_dark },
    SnacksNotifierInfo     = { fg = c.info, bg = bg_float },
    SnacksNotifierWarn     = { fg = c.warn, bg = bg_float },
    SnacksNotifierError    = { fg = c.error, bg = bg_float },
    SnacksNotifierDebug    = { fg = c.fg_dim, bg = bg_float },
    SnacksNotifierTrace    = { fg = c.control, bg = bg_float },
    SnacksDashboardHeader  = { fg = c.accent, bold = true },
    SnacksDashboardTitle   = { fg = c.accent },
    SnacksDashboardDesc    = { fg = c.fg },
    SnacksDashboardIcon    = { fg = c.control },
    SnacksDashboardKey     = { fg = c.func },
    SnacksDashboardFooter  = { fg = c.fg_muted, italic = true },
    SnacksIndent           = { fg = c.indent },
    SnacksIndentScope      = { fg = c.indent_active },
    SnacksPickerMatch      = { fg = c.accent, bold = true },
    SnacksPickerDir        = { fg = c.fg_muted },
    SnacksPickerBorder     = { fg = c.border_alt, bg = bg_float },
    SnacksPickerTitle      = { fg = c.bg, bg = c.accent, bold = true },

    ---------------------------------------------------------------------------
    -- trouble.nvim / todo-comments.nvim
    ---------------------------------------------------------------------------
    TroubleNormal          = { fg = c.fg, bg = bg_sidebar },
    TroubleNormalNC        = { fg = c.fg, bg = bg_sidebar },
    TroubleText            = { fg = c.fg },
    TroubleCount           = { fg = c.control, bg = c.bg_sel },
    TroubleIndent          = { fg = c.indent },
    TroubleFoldIcon        = { fg = c.fg_dim },
    TroubleLocation        = { fg = c.line_nr },
    TroubleSource          = { fg = c.fg_muted },
    TroubleCode            = { fg = c.fg_muted },
    TroubleFile            = { fg = c.accent },
    TroublePos             = { fg = c.line_nr },
    TroubleIconDirectory   = { fg = c.accent },

    TodoBgTODO             = { fg = c.bg, bg = c.info, bold = true },
    TodoFgTODO             = { fg = c.info },
    TodoSignTODO           = { fg = c.info },
    TodoBgFIX              = { fg = c.bg, bg = c.error, bold = true },
    TodoFgFIX              = { fg = c.error },
    TodoSignFIX            = { fg = c.error },
    TodoBgHACK             = { fg = c.bg, bg = c.warn, bold = true },
    TodoFgHACK             = { fg = c.warn },
    TodoSignHACK           = { fg = c.warn },
    TodoBgWARN             = { fg = c.bg, bg = c.warn, bold = true },
    TodoFgWARN             = { fg = c.warn },
    TodoSignWARN           = { fg = c.warn },
    TodoBgPERF             = { fg = c.bg, bg = c.control, bold = true },
    TodoFgPERF             = { fg = c.control },
    TodoSignPERF           = { fg = c.control },
    TodoBgNOTE             = { fg = c.bg, bg = c.ok, bold = true },
    TodoFgNOTE             = { fg = c.ok },
    TodoSignNOTE           = { fg = c.ok },
    TodoBgTEST             = { fg = c.bg, bg = c.type, bold = true },
    TodoFgTEST             = { fg = c.type },
    TodoSignTEST           = { fg = c.type },

    ---------------------------------------------------------------------------
    -- lazy.nvim / mason.nvim
    ---------------------------------------------------------------------------
    LazyNormal             = { fg = c.fg, bg = bg_float },
    LazyButton             = { fg = c.fg, bg = c.bg_sel },
    LazyButtonActive       = { fg = c.bg, bg = c.accent, bold = true },
    LazyH1                 = { fg = c.bg, bg = c.accent, bold = true },
    LazyH2                 = { fg = c.accent, bold = true },
    LazyComment            = { fg = c.fg_muted },
    LazyProp               = { fg = c.fg_dim },
    LazyReasonPlugin       = { fg = c.control },
    LazyReasonEvent        = { fg = c.func },
    LazyReasonKeys         = { fg = c.type },
    LazyReasonStart        = { fg = c.added },
    LazyReasonSource       = { fg = c.number },
    LazyReasonFt           = { fg = c.accent },
    LazyReasonCmd          = { fg = c.accent },
    LazyReasonImport       = { fg = c.fg },
    LazyProgressDone       = { fg = c.added, bold = true },
    LazyProgressTodo       = { fg = c.border_alt, bold = true },
    LazySpecial            = { fg = c.accent },
    LazyDimmed             = { fg = c.fg_muted },

    MasonNormal            = { fg = c.fg, bg = bg_float },
    MasonHeader            = { fg = c.bg, bg = c.accent, bold = true },
    MasonHeaderSecondary   = { fg = c.bg, bg = c.control, bold = true },
    MasonHighlight         = { fg = c.accent },
    MasonHighlightBlock    = { fg = c.bg, bg = c.accent },
    MasonHighlightBlockBold= { fg = c.bg, bg = c.accent, bold = true },
    MasonMuted             = { fg = c.fg_muted },
    MasonMutedBlock        = { fg = c.fg, bg = c.bg_sel },
    MasonError             = { fg = c.error },

    ---------------------------------------------------------------------------
    -- nvim-dap / nvim-dap-ui
    ---------------------------------------------------------------------------
    DapBreakpoint          = { fg = c.removed },
    DapBreakpointCondition = { fg = c.warn },
    DapLogPoint            = { fg = c.info },
    DapStopped             = { fg = c.warn },
    DapStoppedLine         = { bg = util.blend(c.warn, c.bg, 0.12) },
    DapUIVariable          = { fg = c.variable },
    DapUIScope             = { fg = c.accent },
    DapUIType              = { fg = c.type },
    DapUIValue             = { fg = c.fg },
    DapUIModifiedValue     = { fg = c.accent, bold = true },
    DapUIDecoration        = { fg = c.accent },
    DapUIThread            = { fg = c.added },
    DapUIStoppedThread     = { fg = c.accent },
    DapUISource            = { fg = c.control },
    DapUILineNumber        = { fg = c.line_nr },
    DapUIFloatBorder       = { fg = c.border_alt, bg = bg_float },
    DapUIWatchesEmpty      = { fg = c.error },
    DapUIWatchesValue      = { fg = c.added },
    DapUIWatchesError      = { fg = c.error },
    DapUIBreakpointsPath   = { fg = c.accent },
    DapUIBreakpointsInfo   = { fg = c.added },
    DapUIBreakpointsCurrentLine = { fg = c.added, bold = true },

    ---------------------------------------------------------------------------
    -- flash.nvim / leap.nvim / hop.nvim
    ---------------------------------------------------------------------------
    FlashBackdrop          = { fg = c.fg_muted },
    FlashLabel             = { fg = c.bg, bg = c.control, bold = true },
    FlashMatch             = { fg = c.fg_editor, bg = c.match },
    FlashCurrent           = { fg = c.fg_editor, bg = c.match_cur },
    LeapBackdrop           = { fg = c.fg_muted },
    LeapMatch              = { fg = c.bg, bg = c.control, bold = true },
    LeapLabelPrimary       = { fg = c.bg, bg = c.control, bold = true },
    LeapLabelSecondary     = { fg = c.bg, bg = c.type, bold = true },
    HopNextKey             = { fg = c.control, bold = true },
    HopNextKey1            = { fg = c.accent, bold = true },
    HopNextKey2            = { fg = c.type },
    HopUnmatched           = { fg = c.fg_muted },

    ---------------------------------------------------------------------------
    -- mini.nvim
    ---------------------------------------------------------------------------
    MiniStatuslineDevinfo  = { fg = c.fg, bg = c.bg_sel },
    MiniStatuslineFilename = { fg = c.fg_dim, bg = c.bg_alt },
    MiniStatuslineFileinfo = { fg = c.fg, bg = c.bg_sel },
    MiniStatuslineInactive = { fg = c.fg_dimmer, bg = c.bg_alt },
    MiniStatuslineModeNormal  = { fg = c.bg, bg = c.accent, bold = true },
    MiniStatuslineModeInsert  = { fg = c.bg, bg = c.added, bold = true },
    MiniStatuslineModeVisual  = { fg = c.bg, bg = c.control, bold = true },
    MiniStatuslineModeReplace = { fg = c.bg, bg = c.removed, bold = true },
    MiniStatuslineModeCommand = { fg = c.bg, bg = c.warn, bold = true },
    MiniStatuslineModeOther   = { fg = c.bg, bg = c.type, bold = true },
    MiniTablineCurrent     = { fg = c.fg, bg = bg, bold = true },
    MiniTablineVisible     = { fg = c.fg_dim, bg = c.bg_alt },
    MiniTablineHidden      = { fg = c.fg_dimmer, bg = c.bg_alt },
    MiniTablineModifiedCurrent = { fg = c.warn, bg = bg },
    MiniTablineModifiedVisible = { fg = c.warn, bg = c.bg_alt },
    MiniTablineModifiedHidden  = { fg = c.warn, bg = c.bg_alt },
    MiniTablineFill        = { bg = c.bg_alt },
    MiniTablineTabpagesection = { fg = c.bg, bg = c.accent, bold = true },
    MiniCursorword         = { bg = c.bg_highlight },
    MiniCursorwordCurrent  = { bg = c.bg_highlight },
    MiniHipatternsFixme    = { fg = c.bg, bg = c.error, bold = true },
    MiniHipatternsHack     = { fg = c.bg, bg = c.warn, bold = true },
    MiniHipatternsTodo     = { fg = c.bg, bg = c.info, bold = true },
    MiniHipatternsNote     = { fg = c.bg, bg = c.ok, bold = true },
    MiniJump               = { fg = c.bg, bg = c.control },
    MiniJump2dSpot         = { fg = c.control, bold = true },
    MiniStarterCurrent     = { bold = true },
    MiniStarterHeader      = { fg = c.accent, bold = true },
    MiniStarterFooter      = { fg = c.fg_muted, italic = true },
    MiniStarterItem        = { fg = c.fg },
    MiniStarterItemBullet  = { fg = c.border_alt },
    MiniStarterItemPrefix  = { fg = c.func },
    MiniStarterSection     = { fg = c.accent },
    MiniStarterQuery       = { fg = c.control },
    MiniTrailspace         = { bg = util.blend(c.error, c.bg, 0.25) },

    ---------------------------------------------------------------------------
    -- alpha-nvim / dashboard-nvim
    ---------------------------------------------------------------------------
    AlphaHeader            = { fg = c.accent, bold = true },
    AlphaButtons           = { fg = c.fg },
    AlphaShortcut          = { fg = c.func },
    AlphaFooter            = { fg = c.fg_muted, italic = true },
    DashboardHeader        = { fg = c.accent, bold = true },
    DashboardCenter        = { fg = c.fg },
    DashboardShortCut      = { fg = c.func },
    DashboardFooter        = { fg = c.fg_muted, italic = true },
    DashboardDesc          = { fg = c.fg },
    DashboardKey           = { fg = c.func },
    DashboardIcon          = { fg = c.control },

    ---------------------------------------------------------------------------
    -- Misc
    ---------------------------------------------------------------------------
    IlluminatedWordText    = { bg = c.bg_highlight },
    IlluminatedWordRead    = { bg = c.bg_highlight },
    IlluminatedWordWrite   = { bg = c.bg_highlight, underline = true },

    TreesitterContext          = { bg = c.bg_alt },
    TreesitterContextLineNumber= { fg = c.fg_muted, bg = c.bg_alt },
    TreesitterContextBottom    = { underline = true, sp = c.border },

    RainbowDelimiterRed    = { fg = c.tag },
    RainbowDelimiterYellow = { fg = c.func },
    RainbowDelimiterBlue   = { fg = c.accent },
    RainbowDelimiterOrange = { fg = c.attribute },
    RainbowDelimiterGreen  = { fg = c.number },
    RainbowDelimiterViolet = { fg = c.control },
    RainbowDelimiterCyan   = { fg = c.type },

    NavicIconsFile         = { fg = c.fg },
    NavicIconsModule       = { fg = c.type },
    NavicIconsNamespace    = { fg = c.type },
    NavicIconsClass        = { fg = c.type },
    NavicIconsMethod       = { fg = c.func },
    NavicIconsProperty     = { fg = c.variable },
    NavicIconsField        = { fg = c.variable },
    NavicIconsFunction     = { fg = c.func },
    NavicIconsVariable     = { fg = c.variable },
    NavicIconsConstant     = { fg = c.constant },
    NavicIconsString       = { fg = c.string },
    NavicIconsNumber       = { fg = c.number },
    NavicIconsBoolean      = { fg = c.keyword },
    NavicIconsEnum         = { fg = c.type },
    NavicIconsKeyword      = { fg = c.keyword },
    NavicIconsOperator     = { fg = c.operator },
    NavicText              = { fg = c.fg },
    NavicSeparator         = { fg = c.fg_muted },

    AerialLine             = { bg = c.bg_sel },
    AerialGuide            = { fg = c.indent },
    AerialNormal           = { fg = c.fg, bg = bg_sidebar },

    ScrollbarHandle        = { bg = c.bg_sel },
    ScrollbarSearchHandle  = { fg = c.match_cur, bg = c.bg_sel },
    ScrollbarSearch        = { fg = c.match_cur },
    ScrollbarErrorHandle   = { fg = c.error, bg = c.bg_sel },
    ScrollbarError         = { fg = c.error },
    ScrollbarWarnHandle    = { fg = c.warn, bg = c.bg_sel },
    ScrollbarWarn          = { fg = c.warn },
    ScrollbarInfoHandle    = { fg = c.info, bg = c.bg_sel },
    ScrollbarInfo          = { fg = c.info },
    ScrollbarHintHandle    = { fg = c.hint, bg = c.bg_sel },
    ScrollbarHint          = { fg = c.hint },
    ScrollbarGitAddHandle  = { fg = c.added, bg = c.bg_sel },
    ScrollbarGitChangeHandle = { fg = c.changed, bg = c.bg_sel },
    ScrollbarGitDeleteHandle = { fg = c.removed, bg = c.bg_sel },

    HarpoonBorder          = { fg = c.border_alt, bg = bg_float },
    HarpoonWindow          = { fg = c.fg, bg = bg_float },

    DiffviewNormal         = { fg = c.fg, bg = bg_sidebar },
    DiffviewFilePanelTitle = { fg = c.accent, bold = true },
    DiffviewFilePanelCounter = { fg = c.control, bold = true },
    DiffviewFilePanelFileName = { fg = c.fg },
    DiffviewStatusAdded    = { fg = c.added },
    DiffviewStatusModified = { fg = c.changed },
    DiffviewStatusDeleted  = { fg = c.removed },

    NeogitBranch           = { fg = c.control },
    NeogitRemote           = { fg = c.accent },
    NeogitHunkHeader       = { fg = c.fg, bg = c.bg_sel },
    NeogitHunkHeaderHighlight = { fg = c.accent, bg = c.bg_sel },
    NeogitDiffContextHighlight = { bg = c.bg_alt },
    NeogitDiffAddHighlight = { bg = c.diff_add },
    NeogitDiffDeleteHighlight = { bg = c.diff_delete },

    CopilotSuggestion      = { fg = c.fg_muted, italic = true },
    CopilotAnnotation      = { fg = c.fg_muted, italic = true },

    RenderMarkdownH1Bg     = { fg = c.tag, bg = util.blend(c.tag, c.bg, 0.08) },
    RenderMarkdownH2Bg     = { fg = c.tag, bg = util.blend(c.tag, c.bg, 0.06) },
    RenderMarkdownCode     = { bg = c.bg_alt },
    RenderMarkdownBullet   = { fg = c.property_value },
    RenderMarkdownQuote    = { fg = c.property_value },
    RenderMarkdownDash     = { fg = c.border_alt },
  }
end

return M
